# Generated by Django 4.1.3 on 2022-12-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportmessage',
            old_name='user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='supportmessage',
            old_name='worker',
            new_name='sender',
        ),
    ]
