# Generated by Django 4.1.3 on 2022-12-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_alter_supportmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
    ]
