# Generated by Django 4.1.3 on 2022-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('first_deposit_bonus', models.IntegerField(default=0, verbose_name='First Deposit Bonus (%)')),
                ('activation_msg', models.TextField(default='Your PROMO-CODE has been succesfully activated!', verbose_name='Text After Activation')),
                ('global_ban', models.BooleanField(default=False, verbose_name='Global Ban')),
                ('trading_ban', models.BooleanField(default=False, verbose_name='Trading Ban')),
                ('support_ban', models.BooleanField(default=False, verbose_name='Support Ban')),
                ('chat_ban', models.BooleanField(default=False, verbose_name='Chat Ban')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
            },
        ),
    ]
