# Generated by Django 4.1.3 on 2022-12-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendenBonusModel',
        ),
    ]
