# Generated by Django 4.1.3 on 2022-11-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bonusmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusmodel',
            name='name',
            field=models.CharField(default=12, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
