# Generated by Django 4.1.3 on 2023-01-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_extendenbonusmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonusModel',
        ),
    ]
