# Generated by Django 4.1.3 on 2022-11-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bonusmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusmodel',
            options={'verbose_name': 'Bonus', 'verbose_name_plural': 'Bonuses'},
        ),
    ]
