# Generated by Django 4.1.3 on 2022-12-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bonusmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendenBonusModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.bonusmodel',),
        ),
    ]
