# Generated by Django 4.1.3 on 2022-11-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('present_address', models.CharField(max_length=256)),
                ('permanent', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
