# Generated by Django 4.1.3 on 2022-11-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=510)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
