# Generated by Django 4.1.3 on 2022-12-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_customuser_country_alter_customuser_permanent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
