# Generated by Django 4.1.3 on 2022-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='status',
            field=models.CharField(choices=[('PC', 'Proceed'), ('OK', 'OK'), ('BD', 'Bad')], default='PC', max_length=2),
        ),
    ]
