# Generated by Django 4.1.3 on 2022-12-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userverification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='fee',
            field=models.FloatField(default=0, verbose_name='Network Fee'),
        ),
        migrations.AddField(
            model_name='token',
            name='min',
            field=models.FloatField(default=0, verbose_name='Minimum for Deposit'),
        ),
    ]
