# Generated by Django 4.1.3 on 2023-01-04 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_token_fee_token_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('tag', models.CharField(max_length=25, unique=True, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='P2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='User Name')),
                ('orders', models.PositiveIntegerField(verbose_name='Orders (count)')),
                ('orders_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Orders (percent)')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('status', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='ON', max_length=2, verbose_name='Status')),
                ('method', models.CharField(choices=[('WEB', 'Webmoney'), ('C2C', 'Card to Card'), ('ADV', 'Advcash'), ('SIM', 'Sim-card balance'), ('MAS', 'MasterCard'), ('PAY', 'Payeer'), ('PER', 'Perfect Money'), ('PPL', 'PayPal'), ('PSE', 'Paysend'), ('WSU', 'Western Union'), ('PRI', 'PrivatBank'), ('POK', 'PokerStars'), ('SWT', 'SWIFT'), ('VSA', 'Visa'), ('REV', 'Revolut'), ('SBR', 'Sberbank'), ('CSH', 'Cash'), ('TNK', 'Tinkoff'), ('ALH', 'Alphabank'), ('VTB', 'VTB'), ('RFF', 'Reiffeisen'), ('RCK', 'Rocketbank'), ('PCH', 'Pochta Bank'), ('MIR', 'Mir (Payment system)'), ('NAT', 'National bank transfer'), ('RSB', 'Russian Standart Bank'), ('MTS', 'MTS-bank'), ('GAZ', 'Gazprombank'), ('KYK', 'Kykyryza nank'), ('RNC', 'RNCB Bank'), ('AVG', 'Avangard Bank'), ('TCH', 'Touch Bank'), ('MSK', 'Bank of Moscow'), ('QWI', 'QIWI'), ('SBP', 'SBP'), ('YOO', 'YooMoney'), ('ROS', 'Rosbank'), ('YAN', 'Yandex.Money'), ('MTM', 'MTS Money'), ('OTK', 'Otkritie Bank'), ('HCB', 'Home Credit Bank'), ('SCB', 'Sovcombank'), ('PSB', 'PS Bank'), ('CAA', 'Cash at ATM'), ('RAB', 'Russian Agricultural Bank'), ('USB', 'Uralsib'), ('CMB', 'Credit Bank of Moscow'), ('OTP', 'OTP Bank'), ('BSP', 'Bank Saint Petersburg'), ('RSC', 'Renaissance Credit'), ('UNI', 'UniCredit Bank'), ('CIT', 'Citibank'), ('FOR', 'ForBank'), ('BNP', 'BinancePay'), ('KOR', 'KoronaPay (Zolotaya korona)')], default='VSA', max_length=3, verbose_name='Payment Method')),
                ('limit_start', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limit (start)')),
                ('limit_end', models.PositiveIntegerField(default=5000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limit (end)')),
                ('fiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.fiat', verbose_name='Fiat')),
            ],
        ),
    ]
