# Generated by Django 4.1.3 on 2022-11-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_token_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
    ]
