# Generated by Django 4.1.3 on 2022-11-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
