# Generated by Django 4.1.3 on 2023-01-04 16:03

import django.core.validators
from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_p2p_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2p',
            name='photo',
            field=models.ImageField(default='icon-gf02a4d118_640.png', upload_to=user_profile.models.P2P.image_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='p2p',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
