# Generated by Django 4.1.3 on 2022-11-29 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0007_alter_token_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.CharField(max_length=510, verbose_name='Address for deposit(Your Trust Wallet token)'),
        ),
        migrations.AlterField(
            model_name='token',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='token',
            name='tag',
            field=models.CharField(max_length=25, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to=user_profile.models.UserProfile.image_path),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.token'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
