# Generated by Django 4.1.3 on 2023-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_p2p_limit_end_alter_p2p_limit_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gauth_key',
            field=models.CharField(default='default', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='p2p',
            name='method',
            field=models.CharField(choices=[('WEB', 'Webmoney'), ('C2C', 'Card to Card'), ('ADV', 'Advcash'), ('SIM', 'Sim-card balance'), ('MAS', 'MasterCard'), ('PAY', 'Payeer'), ('PER', 'Perfect Money'), ('PPL', 'PayPal'), ('PSE', 'Paysend'), ('WSU', 'Western Union'), ('PRI', 'PrivatBank'), ('POK', 'PokerStars'), ('SWT', 'SWIFT'), ('VSA', 'Visa'), ('REV', 'Revolut'), ('SBR', 'Sberbank'), ('CSH', 'Cash'), ('TNK', 'Tinkoff'), ('ALH', 'Alphabank'), ('VTB', 'VTB'), ('RFF', 'Reiffeisen'), ('RCK', 'Rocketbank'), ('PCH', 'Pochta Bank'), ('MIR', 'Mir (Payment system)'), ('NAT', 'National bank transfer'), ('RSB', 'Russian Standart Bank'), ('MTS', 'MTS-bank'), ('GAZ', 'Gazprombank'), ('KYK', 'Kykyryza nank'), ('RNC', 'RNCB Bank'), ('AVG', 'Avangard Bank'), ('TCH', 'Touch Bank'), ('MSK', 'Bank of Moscow'), ('QWI', 'QIWI'), ('SBP', 'SBP'), ('YOO', 'YooMoney'), ('ROS', 'Rosbank'), ('YAN', 'Yandex.Money'), ('MTM', 'MTS Money'), ('OTK', 'Otkritie Bank'), ('HCB', 'Home Credit Bank'), ('SCB', 'Sovcombank'), ('PSB', 'PS Bank'), ('CAA', 'Cash at ATM'), ('RAB', 'Russian Agricultural Bank'), ('USB', 'Uralsib'), ('CMB', 'Credit Bank of Moscow'), ('OTP', 'OTP Bank'), ('BSP', 'Bank Saint Petersburg'), ('RSC', 'Renaissance Credit'), ('UNI', 'UniCredit Bank'), ('CIT', 'Citibank'), ('FOR', 'ForBank'), ('BNP', 'BinancePay'), ('KOR', 'KoronaPay (Zolotaya korona)'), ('EXS', 'Exodus')], default='VSA', max_length=3, verbose_name='Payment Method'),
        ),
    ]
