# Generated by Django 4.1.3 on 2023-01-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_customuser_gauth_key_alter_p2p_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gauth_key',
        ),
    ]
