# Generated by Django 4.1.3 on 2022-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_usertoken_token_alter_usertoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
