# Generated by Django 4.1.3 on 2022-11-30 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0011_token_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.CharField(max_length=510, verbose_name='Address for deposit'),
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time')),
                ('type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw'), ('B', 'Bonus')], max_length=1, verbose_name='Type')),
                ('bonus_code', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.token', verbose_name='Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
