# Generated by Django 4.1.3 on 2022-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_token_address_usertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='status',
            field=models.CharField(choices=[('P', 'Process'), ('S', 'Success'), ('F', 'Failed')], default='S', max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
