# Generated by Django 4.1.3 on 2023-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_bonusmodel_alter_usertransaction_bonus_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('val', models.CharField(max_length=255, verbose_name='Value')),
            ],
        ),
    ]
