# Generated by Django 4.1.3 on 2023-01-30 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_siteparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteparameter',
            name='key',
            field=models.CharField(max_length=255, unique=True, verbose_name='Key'),
        ),
        migrations.CreateModel(
            name='StakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Amount')),
                ('stake_period', models.CharField(choices=[('OW', '1 Week'), ('TW', '2 Week'), ('OM', '1 Month'), ('TM', '3 Month')], max_length=2, verbose_name='Stake period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
