# Generated by Django 4.1.3 on 2023-02-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_stakemodel_token_tag_alter_stakemodel_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stakemodel',
            unique_together={('user', 'stake_period')},
        ),
    ]
