# Generated by Django 4.1.3 on 2023-02-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_alter_stakemodel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusmodel',
            options={'verbose_name': 'Бонус', 'verbose_name_plural': 'Бонусы'},
        ),
        migrations.AlterModelOptions(
            name='userreferer',
            options={'verbose_name': 'Мамонт', 'verbose_name_plural': 'Мамонты'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'Токен мамонта', 'verbose_name_plural': 'Токены мамонта'},
        ),
        migrations.AlterField(
            model_name='bonusmodel',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='bonusmodel',
            name='chat_ban',
            field=models.BooleanField(default=False, verbose_name='Запретить чат'),
        ),
        migrations.AlterField(
            model_name='bonusmodel',
            name='global_ban',
            field=models.BooleanField(default=False, verbose_name='Глобальный бан'),
        ),
        migrations.AlterField(
            model_name='bonusmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='bonusmodel',
            name='support_ban',
            field=models.BooleanField(default=False, verbose_name='Запретить Support'),
        ),
        migrations.AlterField(
            model_name='bonusmodel',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.token', verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='bonusmodel',
            name='trading_ban',
            field=models.BooleanField(default=False, verbose_name='Запретить торговлю'),
        ),
        migrations.AlterField(
            model_name='userreferer',
            name='data',
            field=models.CharField(default='Hand Binding', max_length=255, verbose_name='Способ'),
        ),
        migrations.AlterField(
            model_name='userreferer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Мамонт'),
        ),
        migrations.AlterField(
            model_name='userreferer',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Воркер'),
        ),
        migrations.AlterUniqueTogether(
            name='usertoken',
            unique_together={('user', 'token')},
        ),
    ]
