# Generated by Django 4.1.3 on 2023-02-18 16:20

from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_sidmodel_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категория NFT',
                'verbose_name_plural': 'Категории NFT',
            },
        ),
        migrations.CreateModel(
            name='NFTOwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('photo', models.ImageField(default='icon-gf02a4d118_640.png', upload_to=user_profile.models.NFTOwnerModel.image_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Владелец NFT',
                'verbose_name_plural': 'Владелецы NFT',
            },
        ),
        migrations.CreateModel(
            name='NFTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=user_profile.models.NFTModel.image_path, verbose_name='Картинка')),
                ('creator', models.CharField(max_length=255, verbose_name='Создатель')),
                ('network', models.CharField(max_length=255, verbose_name='Сеть')),
                ('contract_address', models.CharField(max_length=255, verbose_name='Адрес контракта')),
                ('id_token', models.PositiveIntegerField(unique=True, verbose_name='ID токена')),
                ('royalty', models.PositiveBigIntegerField(verbose_name='Роялти %')),
                ('fee', models.PositiveBigIntegerField(verbose_name='Комиссия платформы %')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.nftcategorymodel', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.nftownermodel', verbose_name='Владелец')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.token', verbose_name='Токен (цена)')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': "NFT's",
            },
        ),
    ]
