# Generated by Django 4.1.3 on 2023-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_botamodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botamodel',
            options={'verbose_name': 'Бот заявка', 'verbose_name_plural': 'Бот заявки'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
